---
# Extract MongoDB
- name: MongoDB
  host: bt-baf-5g-core_5g-db
  gather_facts: false
  tasks:
    - name: Export MongoDB Accounts
      ansible.builtin.shell: mongoexport --collection=accounts --db=open5gs --out=~/accounts.json
      tags: 
        - db
        - export
    - name: Download MongoDB Accounts
      ansible.builtin.fetch:
        src: ~/accounts.json
        dest: database/accounts.json
      tags: 
        - db
        - download
    - name: Clear Account Export
      ansible.builtin.file:
        path: ~/accounts.json
        state: absent
      tags: 
        - db
        - clear

    - name: Export MongoDB Profiles
      ansible.builtin.shell: mongoexport --collection=profiles --db=open5gs --out=~/profiles.json
      tags: 
        - db
        - export
        - profiles
    - name: Download MongoDB Profiles
      ansible.builtin.fetch:
        src: ~/profiles.json
        dest: database/profiles.json
      tags: 
        - db
        - download
    - name: Clear Profile Export
      ansible.builtin.file:
        path: ~/profiles.json
        state: absent
      tags: 
        - db
        - clear
                
    - name: Export MongoDB Sessions
      ansible.builtin.shell: mongoexport --collection=sessions --db=open5gs --out=~/sessions.json
      tags: 
        - db
        - export
    - name: Download MongoDB Sessions
      ansible.builtin.fetch:
        src: ~/sessions.json
        dest: database/sessions.json
      tags: 
        - db
        - download
    - name: Clear Sessions Export
      ansible.builtin.file:
        path: ~/sessions.json
        state: absent
      tags: 
        - db
        - clear
                
    - name: Export MongoDB Subscribers
      ansible.builtin.shell: mongoexport --collection=subscribers --db=open5gs --out=~/subscribers.json
      tags: 
        - db
        - export
    - name: Download MongoDB Subscribers
      ansible.builtin.fetch:
        src: ~/subscribers.json
        dest: database/subscribers.json
      tags: 
        - db
        - download
    - name: Clear Subscribers Export
      ansible.builtin.file:
        path: ~/subscribers.json
        state: absent
      tags: 
        - db
        - clear

- name: AMF
  hosts: bt_baf_5g_core_5g-amf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/amf.yaml
        dest: nfconfig/amf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - amf

- name: NRF
  hosts: bt_baf_5g_core_5g-nrf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/nrf.yaml
        dest: nfconfig/nrf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - nrf

- name: PCF
  hosts: bt_baf_5g_core_5g-pcf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/pcf.yaml
        dest: nfconfig/pcf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - pcf

- name: UDR
  hosts: bt_baf_5g_core_5g-udr
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/udr.yaml
        dest: nfconfig/udr-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - udr

- name: UDM
  hosts: bt_baf_5g_core_5g-udm
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/udm.yaml
        dest: nfconfig/udm-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - udm

- name: NSSF
  hosts: bt_baf_5g_core_5g-nssf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/nssf.yaml
        dest: nfconfig/nssf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - nssf

- name: AUSF
  hosts: bt_baf_5g_core_5g-ausf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/ausf.yaml
        dest: nfconfig/ausf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - ausf

- name: BSF
  hosts: bt_baf_5g_core_5g-bsf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/bsf.yaml
        dest: nfconfig/bsf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - bsf

- name: SMF
  hosts: bt_baf_5g_core_5g-smf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/smf.yaml
        dest: nfconfig/smf-{{ inventory_hostname }}.yaml
        flat: true
      tags: 
        - smf
    - name: Extract Bird Config File
      ansible.builtin.fetch:
        src: /etc/bird/bird.conf
        dest: birdconf/bird-{{ inventory_hostname }}.conf
        flat: true
      tags:
        - bird

- name: UPF-CORE
  hosts: bt_baf_5g_core_5g-upf-core
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/upf.yaml
        dest: nfconfig/upf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - upf
        - upf-core
    - name: Extract Bird Config File
      ansible.builtin.fetch:
        src: /etc/bird/bird.conf
        dest: birdconf/bird-{{ inventory_hostname }}.conf
        flat: true
      tags:
        - bird

- name: UPF BAF
  hosts: bt_baf_5g_core_5g-upf-baf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/upf.yaml
        dest: nfconfig/upf-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - upf
        - upf-baf

- name: Extract gNB
  hosts: bt-baf-ran_5g-gnb-baf,bt-beg-ran_5g-gnb-beg
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /opt/UERANSIM/config/open5gs-gnb.yaml
        dest: gnbconfig/open5gs-gnb-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - gnb

- name: UE
  hosts: bt-baf-ran_5g-ue-baf_01,bt-baf-ran_5g-ue-baf_02,bt-baf-ran_5g-ue-baf_03
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /opt/UERANSIM/config/open5gs-ue.yaml
        dest: ueconfig/open5gs-ue-{{ inventory_hostname }}.yaml
        flat: true
      tags:
        - ue
