---
# Extract bird conf
# Extract MongoDB

- name: AMF
  hosts: bt_baf_5g_core_5g-amf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/amf.yaml
        dest: nfconfig/amf-{{ inventory_hostname }}.yaml
        flat: yes

- name: NRF
  hosts: bt_baf_5g_core_5g-nrf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/nrf.yaml
        dest: nfconfig/nrf-{{ inventory_hostname }}.yaml
        flat: yes

- name: PCF
  hosts: bt_baf_5g_core_5g-pcf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/pcf.yaml
        dest: nfconfig/pcf-{{ inventory_hostname }}.yaml
        flat: yes

- name: UDR
  hosts: bt_baf_5g_core_5g-udr
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/udr.yaml
        dest: nfconfig/udr-{{ inventory_hostname }}.yaml
        flat: yes

- name: UDM
  hosts: bt_baf_5g_core_5g-udm
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/udm.yaml
        dest: nfconfig/udm-{{ inventory_hostname }}.yaml
        flat: yes

- name: NSSF
  hosts: bt_baf_5g_core_5g-nssf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/nssf.yaml
        dest: nfconfig/nssf-{{ inventory_hostname }}.yaml
        flat: yes

- name: AUSF
  hosts: bt_baf_5g_core_5g-ausf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/ausf.yaml
        dest: nfconfig/ausf-{{ inventory_hostname }}.yaml
        flat: yes

- name: BSF
  hosts: bt_baf_5g_core_5g-bsf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/bsf.yaml
        dest: nfconfig/bsf-{{ inventory_hostname }}.yaml
        flat: yes

- name: SMF
  hosts: bt_baf_5g_core_5g-smf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/smf.yaml
        dest: nfconfig/smf-{{ inventory_hostname }}.yaml
        flat: yes

- name: UPF-CORE
  hosts: bt_baf_5g_core_5g-upf-core
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/upf.yaml
        dest: nfconfig/upf-{{ inventory_hostname }}.yaml
        flat: yes

- name: UPF BAF
  hosts: bt_baf_5g_core_5g-upf-baf
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /etc/open5gs/upf.yaml
        dest: nfconfig/upf-{{ inventory_hostname }}.yaml
        flat: yes

- name: gNB
  hosts: bt-baf-ran_5g-gnb-baf,bt-beg-ran_5g-gnb-beg
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /opt/UERANSIM/config/open5gs-gnb.yaml
        dest: gnbconfig/open5gs-gnb-{{ inventory_hostname }}.yaml
        flat: yes

- name: UE
  hosts: bt-baf-ran_5g-ue-baf_01,bt-baf-ran_5g-ue-baf_02,bt-baf-ran_5g-ue-baf_03
  gather_facts: false
  tasks:
    - name: Extract Config File
      ansible.builtin.fetch:
        src: /opt/UERANSIM/config/open5gs-ue.yaml
        dest: ueconfig/open5gs-ue-{{ inventory_hostname }}.yaml
        flat: yes
