---
- name: Enable IPv6 in UFW Configs
  hosts: linux_5gcore
  gather_facts: false
  become: true
  tasks:
    - name: Enable IPv6
      ansible.builtin.replace:
        path: /etc/default/ufw
        regexp: 'IPV6=no'
        replace: 'IPV6=yes'

- name: Enable UFW and Logging
  hosts: linux_5gcore
  become: true
  gather_facts: false
  tasks:
    - name: Enable UFW and Logging
      community.general.ufw:
        state: enabled
        default: reject
        direction: incoming
        logging: true
    - name: Limit SSH Rates
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: SBI Communication Rules
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
      with_items:
        #DB
        - 10.6.11.10
        - 2a07:1182:6:1002::10
        # NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #UDM
        - 10.6.11.22
        - 2a07:1182:6:1002::22
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #AUSF
        - 10.6.11.24
        - 2a07:1182:6:1002::24
        #SMF
        - 10.6.11.26
        - 2a07:1182:6:1002::26
        #PCF
        - 10.6.11.27
        - 2a07:1182:6:1002::27
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28
        #NSSF
        - 10.6.11.23
        - 2a07:1182:6:1002::23
        #WEBUI
        - 10.6.11.100
        - 2a07:1182:6:1002::100

- name: Control Plane Rules
  hosts: linux_5gcore
  become: true
  gather_facts: false
  tasks:
    - name: SBI
      community.general.ufw:
        rule: allow
        port: 7777
        proto: tcp

  - name: AUSF Rules
    hosts: bt-baf-5g-core_5g-amf
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        # AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        # UDM
        - 10.6.11.22
        - 2a07:1182:6:1002::22
        # NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28

  - name: NRF Rules
    hosts: bt-baf-5g-core_5g-nrf
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #WEBUI
        - 10.6.11.100
        - 2a07:1182:6:1002::100
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #UDM
        - 10.6.11.22
        - 2a07:1182:6:1002::22
        #NSSF
        - 10.6.11.23
        - 2a07:1182:6:1002::23
        #AUSF
        - 10.6.11.24
        - 2a07:1182:6:1002::24
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #SMF
        - 10.6.11.26
        - 2a07:1182:6:1002::26
        #PCF
        - 10.6.11.27
        - 2a07:1182:6:1002::27
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28
        #DB
        - 10.6.11.10
        - 2a07:1182:6:1002::10

  - name: UDM Rules
    hosts: bt-baf-5g-core_5g-udm
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #WEBUI
        - 10.6.11.100
        - 2a07:1182:6:1002::100
        #AUSF
        - 10.6.11.24
        - 2a07:1182:6:1002::24
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #SMF
        - 10.6.11.26
        - 2a07:1182:6:1002::26
        #NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28

  - name: UDR Rules
    hosts: bt-baf-5g-core_5g-udr
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #PCF
        - 10.6.11.27
        - 2a07:1182:6:1002::27
        #UDM
        - 10.6.11.22
        - 2a07:1182:6:1002::22
        #NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #DB
        - 10.6.11.10
        - 2a07:1182:6:1002::10
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28

  - name: PCF Rules
    hosts: bt-baf-5g-core_5g-pcf
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #DB
        - 10.6.11.10
        - 2a07:1182:6:1002::10
        #NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #SMF
        - 10.6.11.26
        - 2a07:1182:6:1002::26
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28

  - name: NSSF Rules
    hosts: bt-baf-5g-core_5g-nssf
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28

  - name: BSF Rules #Do not touch first (Allow anyany)
    hosts: bt-baf-5g-core_5g-bsf
    remote_user: open5g
    become: true
    become_method: sudo
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #DB
        - 10.6.11.10
        - 2a07:1182:6:1002::10
        # NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #UDM
        - 10.6.11.22
        - 2a07:1182:6:1002::22
        #AMF
        - 10.6.11.25
        - 2a07:1182:6:1002::25
        #AUSF
        - 10.6.11.24
        - 2a07:1182:6:1002::24
        #SMF
        - 10.6.11.26
        - 2a07:1182:6:1002::26
        #PCF
        - 10.6.11.27
        - 2a07:1182:6:1002::27
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28
        #NSSF
        - 10.6.11.23
        - 2a07:1182:6:1002::23
        #WEBUI
        - 10.6.11.100
        - 2a07:1182:6:1002::100
        

  - name: DB Rules
    hosts: bt-baf-5g-core_5g-db
    become: true
    gather_facts: false
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      with_items:
        #PCF
        - 10.6.11.27
        - 2a07:1182:6:1002::27
        #UDR
        - 10.6.11.21
        - 2a07:1182:6:1002::21
        #NRF
        - 10.6.11.20
        - 2a07:1182:6:1002::20
        #WEBUI
        - 10.6.11.100
        - 2a07:1182:6:1002::100
        #BSF
        - 10.6.11.28
        - 2a07:1182:6:1002::28
