---
- name: Enable IPv6 in UFW Configs
  hosts: open5g
  gather_facts: false
  remote_user: open5g
  become: true
  become_method: sudo
  tasks:
    - name: Enable IPv6
      ansible.builtin.replace:
        path: /etc/default/ufw
        regexp: 'IPV6=no'
        replace: 'IPV6=yes'

- name: Enable UFW and Logging
  hosts: open5g
  remote_user: open5g
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Enable UFW and Logging
      community.general.ufw:
        state: enabled
        default: reject
        direction: incoming
        logging: true
    - name: Limit SSH Rates
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: SBI Communication Rules
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
      with_items:
        - 10.1.11.32  # AMF
        - 10.1.11.33  # SMF
        - 10.1.11.34  # UPF
        - 10.1.11.38  # AUSF
        - 10.1.11.30  # NRF
        - 10.1.11.37  # UDM
        - 10.1.11.36  # UDR
        - 10.1.11.35  # PCF
        - 10.1.11.39  # NSSF
        - 10.1.11.40  # BSF
        - 10.1.11.31  # DB
        - 10.1.11.66  # WebUI
        - 10.1.11.132/25 # RAN
        - 100.99.1.0/24 # UE

- name: Control Plane Rules
  hosts: control_plane
  remote_user: open5g
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: SBI
      community.general.ufw:
        rule: allow
        port: 7777
        proto: tcp

# - name: User Plane Rules
#   hosts: user_plane
#   remote_user: open5g
#   become: true
#   become_method: sudo
#   gather_facts: false
#   tasks:
#     - name: UP N3
#       community.general.ufw:
#         rule: allow
#         port: 2152
#         proto: udp
#     - name: UP N4
#       community.general.ufw:
#         rule: allow
#         port: 8805
#         proto: udp
#     - name: UP BGP
#       community.general.ufw:
#         rule: allow
#         port: 8805179
#         proto: tcp

# - name: AMF Rules
#   hosts: amf
#   remote_user: open5g
#   become: true
#   become_method: sudo
#   gather_facts: false
#   tasks:
#     - name: AMF N2
#       community.general.ufw:
#         rule: allow
#         port: 38412
#         proto: sctp
#     - name: SMF N4
#       community.general.ufw:
#         rule: allow
#         port: 8805
#         proto: udp

# - name: SMF Rules
#   hosts: smf
#   remote_user: open5g
#   become: true
#   become_method: sudo
#   gather_facts: false
#   tasks:
#     - name: SMF N4
#       community.general.ufw:
#         rule: allow
#         port: 8805
#         proto: udp

# - name: DB Rules
#   hosts: db
#   remote_user: open5g
#   become: true
#   become_method: sudo
#   gather_facts: false
#   tasks:
#     - name: Mongo
#       community.general.ufw:
#         rule: allow
#         port: 27017
#         proto: tcp

# - name: WebUI Rules
#   hosts: webui
#   remote_user: open5g
#   become: true
#   become_method: sudo
#   gather_facts: false
#   tasks:
#     - name: HTTP
#       community.general.ufw:
#         rule: allow
#         port: [80, 3000]
#         proto: tcp
#     - name: HTTPS
#       community.general.ufw:
#         rule: allow
#         port: [443]
#         proto: tcp



#only SBI layer IPV4 and 6
    # - name: UPF Rules #(Maybe dont touch this)
    #   hosts: baf-5g-upf
    #   remote_user: open5g
    #   become: true
    #   become_method: sudo
    #   gather_facts: false
    #   community.general.ufw:
    #     rule: allow
    #     src: '{{ item }}'
    #     with_items:
    #       # PCF
    #       - 10.6.11.27
    #       - 2a07:1182:6:1002::27
    #       #WEBUI (only SBI)
    #       - 10.6.11.100
    #       - 2a07:1182:6:1002::100
    #       #UDR
    #       - 10.6.11.21
    #       - 2a07:1182:6:1002::21
    #       #UDM
    #       - 10.6.11.22
    #       - 2a07:1182:6:1002::22
    #       #NSSF
    #       - 10.6.11.23
    #       - 2a07:1182:6:1002::23
    #       #AUSF
    #       - 10.6.11.24
    #       - 2a07:1182:6:1002::24
    #       #AMF (only SBI)
    #       - 10.6.11.25
    #       - 2a07:1182:6:1002::25
    #       #SMF (only SBI)
    #       - 10.6.11.26
    #       - 2a07:1182:6:1002::26
    #       #BSF
    #       - 10.6.11.28
    #       - 2a07:1182:6:1002::28
    #       #DB
    #       - 10.6.11.10
    #       - 2a07:1182:6:1002::10

    - name: AUSF Rules
      hosts: baf-5g-ausf
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          # AMF
          - 10.6.11.25
          - 2a07:1182:6:1002::25
          # UDM
          - 10.6.11.22
          - 2a07:1182:6:1002::22
          # NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28

    - name: NRF Rules
      hosts: baf-5g-nrf
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #WEBUI
          - 10.6.11.100
          - 2a07:1182:6:1002::100
          #UDR
          - 10.6.11.21
          - 2a07:1182:6:1002::21
          #UDM
          - 10.6.11.22
          - 2a07:1182:6:1002::22
          #NSSF
          - 10.6.11.23
          - 2a07:1182:6:1002::23
          #AUSF
          - 10.6.11.24
          - 2a07:1182:6:1002::24
          #AMF
          - 10.6.11.25
          - 2a07:1182:6:1002::25
          #SMF
          - 10.6.11.26
          - 2a07:1182:6:1002::26
          #PCF
          - 10.6.11.27
          - 2a07:1182:6:1002::27
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28
          #DB
          - 10.6.11.10
          - 2a07:1182:6:1002::10

    - name: UDM Rules
      hosts: baf-5g-udm
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #UDR
          - 10.6.11.21
          - 2a07:1182:6:1002::21
          #WEBUI
          - 10.6.11.100
          - 2a07:1182:6:1002::100
          #AUSF
          - 10.6.11.24
          - 2a07:1182:6:1002::24
          #AMF
          - 10.6.11.25
          - 2a07:1182:6:1002::25
          #SMF
          - 10.6.11.26
          - 2a07:1182:6:1002::26
	        #NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28

    - name: UDR Rules
      hosts: baf-5g-udr
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #PCF
          - 10.6.11.27
          - 2a07:1182:6:1002::27
          #UDM
          - 10.6.11.22
          - 2a07:1182:6:1002::22
          #NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #DB
          - 10.6.11.10
          - 2a07:1182:6:1002::10
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28

    - name: PCF Rules
      hosts: baf-5g-pcf
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #AMF
          - 10.6.11.25
          - 2a07:1182:6:1002::25
          #DB
          - 10.6.11.10
          - 2a07:1182:6:1002::10
          #NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #SMF
          - 10.6.11.26
          - 2a07:1182:6:1002::26
          #UDR
          - 10.6.11.21
          - 2a07:1182:6:1002::21
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28

    - name: NSSF Rules
      hosts: baf-5g-nssf
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #AMF
          - 10.6.11.25
          - 2a07:1182:6:1002::25
          #NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28

    # - name: BSF Rules #Do not touch first (Allow anyany)
    #   hosts: baf-5g-bsf
    #   remote_user: open5g
    #   become: true
    #   become_method: sudo
    #   gather_facts: false
    #   community.general.ufw:
    #     rule: allow
    #     src: '{{ item }}'
    #     with_items:
    #       #NRF

    - name: DB Rules
      hosts: baf-5g-db
      remote_user: open5g
      become: true
      become_method: sudo
      gather_facts: false
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        with_items:
          #PCF
          - 10.6.11.27
          - 2a07:1182:6:1002::27
          #UDR
          - 10.6.11.21
          - 2a07:1182:6:1002::21
          #NRF
          - 10.6.11.20
          - 2a07:1182:6:1002::20
          #WEBUI
          - 10.6.11.100
          - 2a07:1182:6:1002::100
          #BSF
          - 10.6.11.28
          - 2a07:1182:6:1002::28
