---
- name: DB
  hosts: bt-baf-5g-core_5g-db
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart mongod
      ignore_errors: true
      tags:
        - db

- name: NRF
  hosts: bt-baf-5g-core_5g-nrf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-nrfd
      tags:
        - nrf
      
- name: UDR
  hosts: bt-baf-5g-core_5g-udr
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-udrd
      tags:
        - nrf
        - db
      
- name: UDM
  hosts: bt-baf-5g-core_5g-udm
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-udmd
      tags:
        - nrf

- name: AUSF
  hosts: bt-baf-5g-core_5g-ausf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-ausfd
      tags:
        - nrf
        - ausf

- name: AMF
  hosts: bt-baf-5g-core_5g-amf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-amfd
      tags:
        - nrf
        - ausf
        - ue

- name: SMF
  hosts: bt-baf-5g-core_5g-smf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-smfd
      tags:
        - nrf
        - ausf
        - ue

- name: UPF-CORE
  hosts: bt-baf-5g-core_5g-upf-core
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-upfd
      tags:
        - nrf
        - ausf
        - ue
    - name: Restart Bird Service
      ansible.builtin.shell: systemctl restart bird.service
      ignore_errors: true
      tags:
        - nrf
        - ausf
        - ue
    - name: Restart systemd-networkd Service
      ansible.builtin.shell: systemctl restart systemd-networkd.service
      ignore_errors: true
      tags:
        - nrf
        - ausf
        - ue

- name: UPF BAF
  hosts: bt-baf-5g-core_5g-upf-baf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-upfd
      tags:
        - nrf
        - ausf
        - ue
    - name: Restart Bird Service
      ansible.builtin.shell: systemctl restart bird.service.
      ignore_errors: true
      tags:
        - nrf
        - ausf
        - ue

- name: PCF
  hosts: bt-baf-5g-core_5g-pcf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-pcfd
      tags:
        - nrf
        - db

- name: BSF
  hosts: bt-baf-5g-core_5g-bsf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-bsfd
      tags:
        - nrf

- name: NSSF
  hosts: bt-baf-5g-core_5g-nssf
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-nssfd
      tags:
        - nrf

- name: WebUI
  hosts: bt-baf-5g-core_5g-webui
  gather_facts: false
  become: true
  tasks:
    - name: Restart Service
      ansible.builtin.shell: systemctl start open5gs-webui
      tags:
        - nrf
        - db