---
- name: NRF
  hosts: bt_baf_5g_core_5g-nrf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/amf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/nrf.yaml
        mode: '0644'
      tags:
        - upf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-nrfd
      tags:
        - upf
        - restart

- name: UDR
  hosts: bt_baf_5g_core_5g-udr
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/udr-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/udr.yaml
        mode: '0644'
      tags:
        - udr
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-udrd
      tags:
        - udr
        - restart

- name: UDM
  hosts: bt_baf_5g_core_5g-udm
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/udm-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/udm.yaml
        mode: '0644'
      tags:
        - udm
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-udmd
      tags:
        - udm
        - restart

- name: AMF
  hosts: bt_baf_5g_core_5g-amf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/amf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/amf.yaml
        mode: '0644'
      tags:
        - amf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-amfd
      tags:
        - amf
        - restart

- name: AUSF
  hosts: bt_baf_5g_core_5g-ausf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/ausf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/ausf.yaml
        mode: '0644'
      tags:
        - ausf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-ausfd
      tags:
        - ausf
        - restart

- name: SMF
  hosts: bt_baf_5g_core_5g-smf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/smf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/smf.yaml
        mode: '0644'
      tags:
        - smf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-smfd
      tags:
        - smf
        - restart

- name: UPF-CORE
  hosts: bt_baf_5g_core_5g-upf-core
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/upf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/upf.yaml
        mode: '0644'
      tags:
        - upf-core
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-upfd
      tags:
        - upf-core
        - restart

- name: UPF BAF
  hosts: bt_baf_5g_core_5g-upf-baf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/upf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/upf.yaml
        mode: '0644'
      tags:
        - upf-baf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-upfd
      tags:
        - upf-baf
        - restart

- name: PCF
  hosts: bt_baf_5g_core_5g-pcf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/pcf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/pcf.yaml
        mode: '0644'
      tags:
        - pcf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-pcfd
      tags:
        - pcf
        - restart

- name: BSF
  hosts: bt_baf_5g_core_5g-bsf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/bsf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/bsf.yaml
        mode: '0644'
      tags:
        - bsf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-bsfd
      tags:
        - bsf
        - restart

- name: NSSF
  hosts: bt_baf_5g_core_5g-nssf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: nfconfig/nssf-{{ inventory_hostname }}.yaml
        dest: /etc/open5gs/nssf.yaml
        mode: '0644'
      tags:
        - nssf
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart open5gs-nssfd
      tags:
        - nssf
        - restart

- name: Upload gNB
  hosts: bt-baf-ran_5g-gnb-baf,bt-beg-ran_5g-gnb-beg
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: gnbconfig/open5gs-gnb-{{ inventory_hostname }}.yaml
        dest: /opt/UERANSIM/config/open5gs-gnb.yaml
        mode: '0644'
      tags:
        - gnb
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart nr-gnb
      tags:
        - gnb
        - restart

- name: UE
  hosts: bt-baf-ran_5g-ue-baf_01,bt-baf-ran_5g-ue-baf_02,bt-baf-ran_5g-ue-baf_03
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: ueconfig/open5gs-ue-{{ inventory_hostname }}.yaml
        dest: /opt/UERANSIM/config/open5gs-ue.yaml
        mode: '0644'
      tags:
        - ue
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart nr-ue
      tags:
        - ue
        - restart

- name: BAF UPF Bird
  hosts: bt-baf-dmz_5g-upf-baf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: birdconf/bird-{{ inventory_hostname }}.conf
        dest: /etc/bird/bird.conf
        mode: '0644'
      tags:
        - upf-baf-bird
        - upload
    - name: Restart Service
      ansible.builtin.shell: ssystemctl restart bird.service
      tags:
        - upf-baf-bird
        - restart

- name: CORE UPF Bird
  hosts: bt-baf-5g-core_5g-upf-core
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: birdconf/bird-{{ inventory_hostname }}.conf
        dest: /etc/bird/bird.conf
        mode: '0644'
      tags:
        - upf-core-bird
        - upload
    - name: Restart Service
      ansible.builtin.shell: systemctl restart bird.service
      tags:
        - upf-core-bird
        - restart
