---
- name: NRF
  hosts: bt-baf-5g-core_5g-nrf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-nrf.yaml
        dest: /etc/open5gs/nrf.yaml
        mode: '0666'
      tags:
        - nrf

- name: UDR
  hosts: bt-baf-5g-core_5g-udr
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-udr.yaml
        dest: /etc/open5gs/udr.yaml
        mode: '0666'
      tags:
        - udr

- name: UDM
  hosts: bt-baf-5g-core_5g-udm
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-udm.yaml
        dest: /etc/open5gs/udm.yaml
        mode: '0666'
      tags:
        - udm

- name: AUSF
  hosts: bt-baf-5g-core_5g-ausf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-ausf.yaml
        dest: /etc/open5gs/ausf.yaml
        mode: '0666'
      tags:
        - ausf

- name: AMF
  hosts: bt-baf-5g-core_5g-amf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-amf.yaml
        dest: /etc/open5gs/amf.yaml
        mode: '0666'
      tags:
        - amf

- name: SMF
  hosts: bt-baf-5g-core_5g-smf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-smf.yaml
        dest: /etc/open5gs/smf.yaml
        mode: '0666'
      tags:
        - smf

- name: UPF-CORE
  hosts: bt-baf-5g-core_5g-upf-core
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-upf-core.yaml
        dest: /etc/open5gs/upf.yaml
        mode: '0666'
      tags:
        - upf-core

- name: UPF BAF
  hosts: bt-baf-dmz_5g-upf-baf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-dmz_5g-upf-baf.yaml
        dest: /etc/open5gs/upf.yaml
        mode: '0666'
      tags:
        - upf-baf

- name: PCF
  hosts: bt-baf-5g-core_5g-pcf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-pcf.yaml
        dest: /etc/open5gs/pcf.yaml
        mode: '0666'
      tags:
        - pcf

- name: BSF
  hosts: bt-baf-5g-core_5g-bsf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-bsf.yaml
        dest: /etc/open5gs/bsf.yaml
        mode: '0666'
      tags:
        - bsf

- name: NSSF
  hosts: bt-baf-5g-core_5g-nssf
  gather_facts: false
  become: true
  tasks:
    - name: Upload Config File
      ansible.builtin.copy:
        src: log_enabled_nf_config/bt-baf-5g-core_5g-nssf.yaml
        dest: /etc/open5gs/nssf.yaml
        mode: '0666'
      tags:
        - nssf
        